# Generated by Django 4.1.7 on 2023-03-20 07:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, null=True, unique=True),
        ),
    ]
