# Generated by Django 4.1.7 on 2023-03-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0005_supplier_supplier_unique_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=255)),
                ('size', models.FloatField(default=0)),
                ('unit_of_measurement', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('L', 'Liter'), ('ml', 'Milliliter')], max_length=2)),
                ('quantity', models.IntegerField(default=0)),
                ('alert_quantity', models.IntegerField(default=0)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('imported_date', models.DateField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory_Management.supplier')),
            ],
        ),
    ]
