# Generated by Django 4.1.7 on 2023-03-22 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0006_itemdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='imported_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='unit_of_measurement',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter')], max_length=2),
        ),
    ]
