# Generated by Django 4.1.7 on 2023-03-22 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0007_alter_itemdetails_imported_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='imported_date',
            field=models.DateField(default=datetime.date(2023, 3, 22)),
        ),
    ]
