# Generated by Django 4.1.7 on 2023-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0008_alter_itemdetails_imported_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='imported_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
