# Generated by Django 4.1.7 on 2023-03-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0009_alter_itemdetails_imported_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
