# Generated by Django 4.1.7 on 2023-03-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0010_business_business_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Stationary', 'Stationary'), ('Grocery', 'Grocery'), ('Restaurant', 'Restaurant')], max_length=100, null=True),
        ),
    ]
