# Generated by Django 4.1.7 on 2023-04-10 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0011_alter_business_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
