# Generated by Django 4.1.7 on 2023-04-10 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0012_itemdetails_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_vpa', models.CharField(max_length=255)),
                ('payee_name', models.CharField(max_length=255)),
                ('merchant_code', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
