# Generated by Django 4.1.7 on 2023-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
