# Generated by Django 4.1.7 on 2023-04-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0015_transaction_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='units',
            new_name='item_id',
        ),
    ]
