# Generated by Django 4.1.7 on 2023-04-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_Management', '0016_rename_units_transaction_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
