# Generated by Django 4.1.7 on 2023-04-21 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0018_itemdetails_daystostockout"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemdetails",
            name="daystostockout",
        ),
    ]
