# Generated by Django 4.1.7 on 2023-04-21 16:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0019_remove_itemdetails_daystostockout"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdetails",
            name="cogs",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
