# Generated by Django 4.1.5 on 2023-05-02 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0022_remove_cart_items_cartitem_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="quantity",
        ),
    ]
