# Generated by Django 4.1.5 on 2023-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0026_passwordresetrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("added", "Added"), ("sold", "Sold")],
                default="sold",
                max_length=20,
            ),
        ),
    ]
