# Generated by Django 4.1.5 on 2023-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0027_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Added", "Added"), ("Sold", "Sold")],
                default="sold",
                max_length=20,
            ),
        ),
    ]
