# Generated by Django 4.1.5 on 2023-05-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Inventory_Management",
            "0028_alter_transaction_status_alter_transaction_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("added", "Added"), ("sold", "Sold")],
                default="sold",
                max_length=20,
            ),
        ),
    ]
