# Generated by Django 4.1.5 on 2023-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Inventory_Management",
            "0029_alter_transaction_status_alter_transaction_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("employee", "Employee")],
                default="worker",
                max_length=20,
            ),
        ),
    ]
