# Generated by Django 4.1.5 on 2023-05-24 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0030_customuser_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
