# Generated by Django 4.1.5 on 2023-05-26 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory_Management", "0033_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_made_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
