name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Inven-Mangement"]
    types: 
      - completed

jobs:
  login:
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' && ${{ github.event.workflow_run.head_branch == 'main'}}

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with: 
          file: ./Dockerfile
          push: true
          tags: kartiksheoran1/inven-app:v3
