name: Deploy to DockerHub

on:
  push:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}