name: Deploy to Server

on:
  workflow_run:
    workflows: ["Deploy to DockerHub"]
    types: 
      - completed

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Execute remote ssh commands using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          sudo docker pull kartiksheoran1/inven-app:v3
          cd /home/ubuntu
          sudo docker-compose up
